SELECT USER_ID, NICKNAME, CONCAT_WS(" ",CITY,STREET_ADDRESS1,STREET_ADDRESS2) AS 전체주소, CONCAT_WS("-",SUBSTRING(TLNO,1,3),SUBSTRING(TLNO,4,4), SUBSTRING(TLNO,8,4)) AS 전화번호
FROM (
    SELECT *, COUNT(USER_ID) AS CNT
    FROM USED_GOODS_USER AS T1
    JOIN USED_GOODS_BOARD AS T2 ON T1.USER_ID = T2.WRITER_ID
    GROUP BY USER_ID
) AS T3
WHERE T3.CNT >= 3
ORDER BY USER_ID DESC