SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS T1
JOIN USED_GOODS_USER AS T2 ON T1.WRITER_ID=T2.USER_ID
WHERE STATUS='DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES>=700000
ORDER BY TOTAL_SALES